#!/usr/bin/env bash
# $1 = command to run, commands:
# - start: start Transmission container
# - status: get status of container, outputs "running" if Transmission server is running,
#           "stopped" if the Transmission container is stopped but still exists, and
#           "not found" if the Transmission container does not exist.
prog_dir=$(dirname $(realpath "$0"))

function die() {
    echo "transmission: $@" >&2
    exit 1
}

if [ -z "$CONTAINER_CLI" ]; then
    CONTAINER_CLI="sudo podman"
fi

container_name=dev-harvest-transmission-daemon
container_tag="linuxserver/transmission:latest"

host_dl_dir="$prog_dir/container-data/download"
guest_dl_dir="/download"

mkdir -p "$host_dl_dir"

case "$1" in
    start)
	   case $($0 status) in
		  running) die "already running" ;;
		  stopped) $CONTAINER_CLI start "$container_name" ;;
		  "not found")
              $CONTAINER_CLI run \
                             -d \
                             --net host \
                             -v "$host_dl_dir:$guest_dl_dir" \
                             --name "$container_name" \
                             "$container_tag"
              ;;
	   esac
	   ;;
    status)
	   if $CONTAINER_CLI ps | grep "$container_name" &> /dev/null; then
		  echo "running"
	   elif $CONTAINER_CLI ps -a | grep "$container_name" &> /dev/null; then
		  echo "stopped"
	   else
		  echo "not found"
	   fi
	   ;;
    stop)
	   case $($0 status) in
		  running)
			 $CONTAINER_CLI stop "$container_name"
			 $CONTAINER_CLI rm "$container_name"
			 ;;
		  stopped)
			 $CONTAINER_CLI rm "$container_name"
			 ;;
		  *) die "Cannot stop and remove transmission if not running" ;;
	   esac
	   ;;
    logs)
	   case $($0 status) in
		  running)
			 $CONTAINER_CLI logs -f "$container_name"
			 ;;
		  *) die "Cannot get logs if Transmission is not running" ;;
	   esac
	   ;;
    cli)
	   shift
	   $CONTAINER_CLI run -it --rm --net host "$container_tag" transmission $@
	   ;;
    *)
	   die "first argument must be \"start\", \"status\", \"stop\", \"logs\", \"cli\""
	   ;;
esac

